#!/bin/sh
DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
CP=""
for jar in $DIR/*.jar
do
   CP=$CP:$jar
done
for file in $DIR/resources
do
 CP=$CP:$jar
done
PROGRAM=${1-barents.Barents}
shift
exec java -cp $CP org.sufrin.glyph.tests.$PROGRAM "$@"



 