/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MacFreeSpace */

#ifndef _Included_MacFreeSpace
#define _Included_MacFreeSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MacFreeSpace
 * Method:    getImportantAvailableSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_MacFreeSpace_getImportantAvailableSpace
  (JNIEnv *, jclass, jstring);

/*
 * Class:     MacFreeSpace
 * Method:    getOpportunisticAvailableSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_MacFreeSpace_getOpportunisticAvailableSpace
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
